#!/usr/bin/env node
/**
 * Regenerate src/data/index.ts from whatever batch files exist in
 * src/data/challenges/. Run it after adding or removing a batch:
 *
 *   npm run content:index
 *
 * Hard-coded imports (rather than import.meta.glob) keep the module loadable by
 * Vite, esbuild and plain tsc alike.
 */
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHALLENGE_DIR = path.join(ROOT, 'src', 'data', 'challenges');
const OUT = path.join(ROOT, 'src', 'data', 'index.ts');

const identifier = (name) =>
  'batch_' + name.replace(/\.ts$/, '').replace(/[^a-zA-Z0-9]+/g, '_');

const files = (await readdir(CHALLENGE_DIR)).filter((f) => f.endsWith('.ts')).sort();

if (!files.length) {
  console.error('No challenge batches found in src/data/challenges/');
  process.exit(1);
}

const imports = files
  .map((f) => `import { challenges as ${identifier(f)} } from './challenges/${f.replace(/\.ts$/, '')}';`)
  .join('\n');

const list = files.map((f) => `  ...${identifier(f)},`).join('\n');

const source = `/* eslint-disable */
/**
 * GENERATED by scripts/build-index.mjs - do not edit by hand.
 * Regenerate with: npm run content:index
 *
 * ${files.length} challenge batch file(s).
 */
import { Challenge, Stage } from '../types';
import { STAGE_META } from './stages';
${imports}

const RAW_CHALLENGES: Challenge[] = [
${list}
];

const STAGE_ORDER = new Map(STAGE_META.map((s, i) => [s.id, i]));

/**
 * Stage order, then authored order within a stage. Batch files are imported
 * alphabetically, which would otherwise open the library on stage 4.
 */
export const ALL_CHALLENGES: Challenge[] = RAW_CHALLENGES.map((c, i) => ({ c, i }))
  .sort((a, b) => {
    const stageDelta =
      (STAGE_ORDER.get(a.c.stageId) ?? 999) - (STAGE_ORDER.get(b.c.stageId) ?? 999);
    if (stageDelta !== 0) return stageDelta;
    return a.c.id.localeCompare(b.c.id) || a.i - b.i;
  })
  .map(({ c }) => c);

/** Challenges grouped by stage, in stage order, preserving authored order. */
export function buildStages(): Stage[] {
  const byStage = new Map<string, Challenge[]>();
  for (const challenge of ALL_CHALLENGES) {
    const bucket = byStage.get(challenge.stageId);
    if (bucket) bucket.push(challenge);
    else byStage.set(challenge.stageId, [challenge]);
  }

  return STAGE_META.map((meta) => ({
    ...meta,
    state: 'Locked' as const,
    challenges: byStage.get(meta.id) ?? []
  }));
}

/** Flat lookup used by the grader and the practice hub. */
export const CHALLENGE_BY_ID: Map<string, Challenge> = new Map(
  ALL_CHALLENGES.map((c) => [c.id, c])
);

export { STAGE_META };
`;

await writeFile(OUT, source, 'utf8');
console.log(`src/data/index.ts regenerated from ${files.length} batch file(s).`);
