/* eslint-disable */
/**
 * GENERATED by scripts/build-index.mjs - do not edit by hand.
 * Regenerate with: npm run content:index
 *
 * 20 challenge batch file(s).
 */
import { Challenge, Stage } from '../types';
import { STAGE_META } from './stages';
import { challenges as batch_algorithms_a } from './challenges/algorithms-a';
import { challenges as batch_algorithms_b } from './challenges/algorithms-b';
import { challenges as batch_backend_apis_a } from './challenges/backend-apis-a';
import { challenges as batch_backend_apis_b } from './challenges/backend-apis-b';
import { challenges as batch_data_structures_a } from './challenges/data-structures-a';
import { challenges as batch_data_structures_b } from './challenges/data-structures-b';
import { challenges as batch_databases_sql_a } from './challenges/databases-sql-a';
import { challenges as batch_databases_sql_b } from './challenges/databases-sql-b';
import { challenges as batch_programming_basics_a } from './challenges/programming-basics-a';
import { challenges as batch_programming_basics_b } from './challenges/programming-basics-b';
import { challenges as batch_python_fundamentals_a } from './challenges/python-fundamentals-a';
import { challenges as batch_python_fundamentals_b } from './challenges/python-fundamentals-b';
import { challenges as batch_real_projects_a } from './challenges/real-projects-a';
import { challenges as batch_real_projects_b } from './challenges/real-projects-b';
import { challenges as batch_system_design_a } from './challenges/system-design-a';
import { challenges as batch_system_design_b } from './challenges/system-design-b';
import { challenges as batch_tooling_testing_a } from './challenges/tooling-testing-a';
import { challenges as batch_tooling_testing_b } from './challenges/tooling-testing-b';
import { challenges as batch_web_development_a } from './challenges/web-development-a';
import { challenges as batch_web_development_b } from './challenges/web-development-b';

const RAW_CHALLENGES: Challenge[] = [
  ...batch_algorithms_a,
  ...batch_algorithms_b,
  ...batch_backend_apis_a,
  ...batch_backend_apis_b,
  ...batch_data_structures_a,
  ...batch_data_structures_b,
  ...batch_databases_sql_a,
  ...batch_databases_sql_b,
  ...batch_programming_basics_a,
  ...batch_programming_basics_b,
  ...batch_python_fundamentals_a,
  ...batch_python_fundamentals_b,
  ...batch_real_projects_a,
  ...batch_real_projects_b,
  ...batch_system_design_a,
  ...batch_system_design_b,
  ...batch_tooling_testing_a,
  ...batch_tooling_testing_b,
  ...batch_web_development_a,
  ...batch_web_development_b,
];

const STAGE_ORDER = new Map(STAGE_META.map((s, i) => [s.id, i]));

/**
 * Stage order, then authored order within a stage. Batch files are imported
 * alphabetically, which would otherwise open the library on stage 4.
 */
export const ALL_CHALLENGES: Challenge[] = RAW_CHALLENGES.map((c, i) => ({ c, i }))
  .sort((a, b) => {
    const stageDelta =
      (STAGE_ORDER.get(a.c.stageId) ?? 999) - (STAGE_ORDER.get(b.c.stageId) ?? 999);
    if (stageDelta !== 0) return stageDelta;
    return a.c.id.localeCompare(b.c.id) || a.i - b.i;
  })
  .map(({ c }) => c);

/** Challenges grouped by stage, in stage order, preserving authored order. */
export function buildStages(): Stage[] {
  const byStage = new Map<string, Challenge[]>();
  for (const challenge of ALL_CHALLENGES) {
    const bucket = byStage.get(challenge.stageId);
    if (bucket) bucket.push(challenge);
    else byStage.set(challenge.stageId, [challenge]);
  }

  return STAGE_META.map((meta) => ({
    ...meta,
    state: 'Locked' as const,
    challenges: byStage.get(meta.id) ?? []
  }));
}

/** Flat lookup used by the grader and the practice hub. */
export const CHALLENGE_BY_ID: Map<string, Challenge> = new Map(
  ALL_CHALLENGES.map((c) => [c.id, c])
);

export { STAGE_META };
